services:
  mysql:
    image: mysql
    container_name: mysql-ezystore
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ezystore
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ezystore-net

volumes:
  mysql-data:

networks:
  ezystore-net:
